apiVersion: apps/v1
kind: Deployment
metadata:
  name: logiciel-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: logiciel-service
  template:
    metadata:
      labels:
        app: logiciel-service
    spec:
      containers:
        - name: user-service
          image: ghcr.io/hammoudihayfa/oacaback/logiciel-service:latest
          ports:
            - containerPort: 8080
