apiVersion: v1
kind: Service
metadata:
  name: logiciel-service
spec:
  selector:
    app: logiciel-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
