apiVersion: v1
kind: Service
metadata:
  name: eureka-service
spec:
  selector:
    app: eureka-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
