apiVersion: apps/v1
kind: Deployment
metadata:
  name: ocr-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ocr-service
  template:
    metadata:
      labels:
        app: ocr-service
    spec:
      containers:
        - name: user-service
          image: ghcr.io/hammoudihayfa/oacaback/ocr-service:latest
          ports:
            - containerPort: 8080
