apiVersion: v1
kind: Service
metadata:
  name: equipement-service
spec:
  selector:
    app: equipement-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
