apiVersion: apps/v1
kind: Deployment
metadata:
  name: agent-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: agent-service
  template:
    metadata:
      labels:
        app: agent-service
    spec:
      containers:
        - name: user-service
          image: ghcr.io/hammoudihayfa/oacaback/agent-service:latest
          ports:
            - containerPort: 8080
