name: CI/CD Pipeline

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

env:
  # Images pour Docker Hub (vos images actuelles)
  USER_SERVICE_IMAGE: hammoudihayfa/user-service:latest
  MAINTENANCE_SERVICE_IMAGE: hammoudihayfa/maintenance-service:latest
  EUREKA_SERVICE_IMAGE: hammoudihayfa/eureka-service:latest
  EMAIL_SERVICE_IMAGE: hammoudihayfa/email-service:latest
  APIGATEWAY_SERVICE_IMAGE: hammoudihayfa/apigateway-service:latest
  OCR_SERVICE_IMAGE: hammoudihayfa/ocr_service:latest
  LOGICIEL_SERVICE_IMAGE: hammoudihayfa/logiciel-service:latest
  EQUIPEMENT_SERVICE_IMAGE: hammoudihayfa/equipement-service:latest
  AGENT_SERVICE_IMAGE: hammoudihayfa/agent-service:latest

  # --- Nouvelles variables d'environnement pour GitHub Container Registry (GHCR) ---
  GHCR_REGISTRY: ghcr.io
  GHCR_OWNER: hammoudihayfa
  GHCR_REPO: oacaback

  # Noms complets des images GHCR (ajustés pour la cohérence des noms de service)
  GHCR_USER_SERVICE_IMAGE: ghcr.io/hammoudihayfa/oacaback/user-service:latest
  GHCR_MAINTENANCE_SERVICE_IMAGE: ghcr.io/hammoudihayfa/oacaback/maintenance-service:latest
  GHCR_EUREKA_SERVICE_IMAGE: ghcr.io/hammoudihayfa/oacaback/eureka-service:latest
  GHCR_EMAIL_SERVICE_IMAGE: ghcr.io/hammoudihayfa/oacaback/email-service:latest
  GHCR_APIGATEWAY_SERVICE_IMAGE: ghcr.io/hammoudihayfa/oacaback/apigateway-service:latest
  GHCR_OCR_SERVICE_IMAGE: ghcr.io/hammoudihayfa/oacaback/ocr_service:latest
  GHCR_LOGICIEL_SERVICE_IMAGE: ghcr.io/hammoudihayfa/oacaback/logiciel-service:latest
  GHCR_EQUIPEMENT_SERVICE_IMAGE: ghcr.io/hammoudihayfa/oacaback/equipement-service:latest
  GHCR_AGENT_SERVICE_IMAGE: ghcr.io/hammoudihayfa/oacaback/agent-service:latest

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Build & Test Microservices
      run: |
        SERVICES="user-service maintenance-service eurekaMs email-service apiGateway ocr_service logiciel-service equipement-service agent-service"
        for SERVICE in $SERVICES; do
          echo "Building $SERVICE..."
          cd $SERVICE
          chmod +x mvnw
          ./mvnw clean install -DskipTests
          ./mvnw test
          cd ..
        done

    - name: Verify compiled binaries paths
      run: |
        echo "Listing contents of target/classes directories:"
        for SERVICE in user-service maintenance-service eurekaMs email-service apiGateway ocr_service logiciel-service equipement-service agent-service; do
          ls -R $SERVICE/target/classes || echo "$SERVICE/target/classes not found or empty"
        done

    - name: SonarCloud Analysis
      uses: SonarSource/sonarqube-scan-action@v5.0.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      with:
        args: >
          -Dsonar.projectKey=hammoudihayfa_OACAback
          -Dsonar.organization=hammoudihayfa
          -Dsonar.java.binaries=user-service/target/classes,maintenance-service/target/classes,eurekaMs/target/classes,email-service/target/classes,apiGateway/target/classes,ocr_service/target/classes,logiciel-service/target/classes,equipement-service/target/classes,agent-service/target/classes
          -Dsonar.host.url=https://sonarcloud.io

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Login to GitHub Container Registry (GHCR)
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build & Push Docker Images (Docker Hub & GHCR)
      run: |
        declare -A DOCKER_HUB_IMAGES=(
          [user-service]=$USER_SERVICE_IMAGE
          [maintenance-service]=$MAINTENANCE_SERVICE_IMAGE
          [eurekaMs]=$EUREKA_SERVICE_IMAGE
          [email-service]=$EMAIL_SERVICE_IMAGE
          [apiGateway]=$APIGATEWAY_SERVICE_IMAGE
          [ocr_service]=$OCR_SERVICE_IMAGE
          [logiciel-service]=$LOGICIEL_SERVICE_IMAGE
          [equipement-service]=$EQUIPEMENT_SERVICE_IMAGE
          [agent-service]=$AGENT_SERVICE_IMAGE
        )

        declare -A GHCR_IMAGES=(
          [user-service]=$GHCR_USER_SERVICE_IMAGE
          [maintenance-service]=$GHCR_MAINTENANCE_SERVICE_IMAGE
          [eurekaMs]=$GHCR_EUREKA_SERVICE_IMAGE
          [email-service]=$GHCR_EMAIL_SERVICE_IMAGE
          [apiGateway]=$GHCR_APIGATEWAY_SERVICE_IMAGE
          [ocr_service]=$GHCR_OCR_SERVICE_IMAGE
          [logiciel-service]=$GHCR_LOGICIEL_SERVICE_IMAGE
          [equipement-service]=$GHCR_EQUIPEMENT_SERVICE_IMAGE
          [agent-service]=$GHCR_AGENT_SERVICE_IMAGE
        )

        for SERVICE_DIR in "${!DOCKER_HUB_IMAGES[@]}"; do
          DOCKER_HUB_IMAGE=${DOCKER_HUB_IMAGES[$SERVICE_DIR]}
          GHCR_IMAGE=${GHCR_IMAGES[$SERVICE_DIR]}

          echo "Building Docker image for $SERVICE_DIR..."
          docker build -t "$DOCKER_HUB_IMAGE" -t "$GHCR_IMAGE" "$SERVICE_DIR"

          echo "Pushing Docker image to Docker Hub: $DOCKER_HUB_IMAGE"
          docker push "$DOCKER_HUB_IMAGE"

          echo "Pushing Docker image to GHCR: $GHCR_IMAGE"
          docker push "$GHCR_IMAGE"
        done

    - name: Install Docker Compose
      run: |
        sudo curl -L "https://github.com/docker/compose/releases/download/v2.24.5/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
        sudo chmod +x /usr/local/bin/docker-compose

    - name: Display docker-compose.yml content
      run: |
        echo "Content of docker-compose.yml:"
        cat docker-compose.yml || echo "docker-compose.yml not found!"

    - name: Deploy with Docker Compose (Local Validation)
      run: |
        docker-compose down --volumes --remove-orphans || true
        docker-compose up -d --build
        docker-compose ps

    - name: Set up Kubeconfig for Kubernetes Deployment
      env:
        KUBECONFIG_BASE64: ${{ secrets.KUBE_CONFIG_BASE64 }}
      run: |
        mkdir -p ~/.kube
        echo "${KUBECONFIG_BASE64}" | base64 -d > ~/.kube/config
        chmod 600 ~/.kube/config
        echo "Kubeconfig configured."
